Repository spring-projects/spring-security, pull requests merged in 2018-03, with the labels that each got.

#5057 Upgrade Nimbus JOSE + JWT to 5.5
  gradle/dependency-management.gradle
Labels: Improvement, JWT-JOSE

#5074 Upgrade Nimbus OAuth + OIDC SDK to 5.56
  gradle/dependency-management.gradle
Labels: Build and Admin, Improvement

#5079 Sec2758Tests groovy->java
  config/src/test/groovy/org/springframework/security/config/annotation/sec2758/Sec2758Tests.groovy
  config/src/test/java/org/springframework/security/config/annotation/sec2758/Sec2758Tests.java
Labels: Build and Admin, Improvement

#5087 Add the BadCredentialsExceptionMixin
  core/src/main/java/org/springframework/security/jackson2/BadCredentialsExceptionMixin.java
  core/src/main/java/org/springframework/security/jackson2/CoreJackson2Module.java
  core/src/test/java/org/springframework/security/jackson2/BadCredentialsExceptionMixinTests.java
Labels: Core, Improvement

#5095 Update to Spring Boot 2.0.0.RELEASE
  gradle.properties
Labels: Build and Admin, Improvement

#5094 Update to Spring Boot 2.0.0.RELEASE
  gradle.properties
Labels: Build and Admin, Improvement, duplicate

#5085 Authorities authenticate TestingAuthenticationToken
  cas/src/test/java/org/springframework/security/cas/web/CasAuthenticationFilterTests.java
  core/src/main/java/org/springframework/security/authentication/TestingAuthenticationToken.java
  core/src/test/java/org/springframework/security/authentication/TestingAuthenticationTokenTests.java
Labels: Bug, Core

#5124 Improve EditorConfig file
  .editorconfig
Labels: Build and Admin, Improvement

#5123 ReactorContextTestExecutionListener should obtain SecurityContext on TestExecutionListenerThread
  test/src/main/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListener.java
  test/src/test/java/org/springframework/security/test/context/support/ReactorContextTestExecutionListenerTests.java
  test/src/test/java/org/springframework/security/test/web/reactive/server/AbstractMockServerConfigurersTests.java
  test/src/test/java/org/springframework/security/test/web/reactive/server/SecurityMockServerConfigurersAnnotatedTests.java
Labels: Bug, Test

#5150 Update User.java
  core/src/main/java/org/springframework/security/core/userdetails/User.java
Labels: Bug, Docs and Website

#5162 Fix @since for StrictHttpFirewall
  web/src/main/java/org/springframework/security/web/firewall/StrictHttpFirewall.java
Labels: Bug, Docs and Website, Web

#5152 Close quoted expected path in log when matching
  web/src/main/java/org/springframework/security/web/util/matcher/AntPathRequestMatcher.java
Labels: Bug, Web
