Repository spring-projects/spring-security, pull requests merged in 2019-10, with the labels that each got.

#7506 Update to Spring Data Moore-RELEASE
  gradle/dependency-management.gradle
Labels: type: dependency-upgrade

#7516 Support configuration of protocol binding for authentication requests
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactory.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationRequestFactoryTests.java
Labels: in: saml2, status: first-timers-only

#7519 Fix typo in Javadoc
  ldap/src/main/java/org/springframework/security/ldap/authentication/ad/ActiveDirectoryLdapAuthenticationProvider.java
Labels: in: docs

#7523 fix webflux samples documentation path
  docs/manual/src/docs/asciidoc/_includes/reactive/webflux.adoc
Labels: in: docs

#7533 Polish AuthorityUtils
  core/src/main/java/org/springframework/security/core/authority/AuthorityUtils.java
Labels: status: waiting-for-triage

#7534 Add Clock Skew Tests
  oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/ClientCredentialsOAuth2AuthorizedClientProviderTests.java
  oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/PasswordOAuth2AuthorizedClientProviderTests.java
  oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/RefreshTokenReactiveOAuth2AuthorizedClientProviderTests.java
Labels: in: oauth2, type: enhancement

#5908 extract permission mask comparison for subclasses to override
  acl/src/main/java/org/springframework/security/acls/domain/DefaultPermissionGrantingStrategy.java
  acl/src/test/java/org/springframework/security/acls/domain/AclImplTests.java
Labels: in: core, type: enhancement

#5941 Use more specific GrantedAuthority for mapped roles
  ldap/src/integration-test/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulatorTests.java
  ldap/src/main/java/org/springframework/security/ldap/userdetails/DefaultLdapAuthoritiesPopulator.java
Labels: status: waiting-for-feedback

#5928 Allow override AbstractPreAuthenticatedProcessingFilter#requiresAuthentication
  web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java
  web/src/test/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilterTests.java
Labels: in: web, type: enhancement

#4142 DefaultRedirectStrategy should not calculate relative url if it does not contain the context-path
  web/src/main/java/org/springframework/security/web/DefaultRedirectStrategy.java
  web/src/test/java/org/springframework/security/web/DefaultRedirectStrategyTests.java
Labels: status: feedback-provided

#7561 Align javadoc of continueFilterChainOnUnsuccessfulAuthentication with actual behaviour
  web/src/main/java/org/springframework/security/web/authentication/preauth/AbstractPreAuthenticatedProcessingFilter.java
Labels: in: docs, type: bug

#7559 Fix typo 'is' -> 'if' in javadoc
  config/src/main/java/org/springframework/security/config/annotation/web/configurers/ExceptionHandlingConfigurer.java
Labels: status: waiting-for-triage

#7571 Fix variable reference in sample code
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/registration/RelyingPartyRegistration.java
Labels: in: saml2, type: enhancement
