Repository spring-projects/spring-security, pull requests merged in 2019-11, with the labels that each got.

#6898 Support URI vars in formLogin and logout MockMvc requests
  test/src/main/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuilders.java
  test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuildersFormLoginTests.java
  test/src/test/java/org/springframework/security/test/web/servlet/request/SecurityMockMvcRequestBuildersFormLogoutTests.java
Labels: in: test, status: feedback-provided, type: enhancement

#7510 Upgrade spring-boot version to latest snapshot
  samples/boot/hellorsocket/src/integration-test/java/sample/HelloRSocketApplicationITests.java
Labels: in: rsocket, status: feedback-provided

#7623 Add missing schemas
  config/src/main/resources/META-INF/spring.schemas
Labels: type: bug

#7590 Clarify usage of hasAnyRole and hasAnyAuthority
  docs/manual/src/docs/asciidoc/_includes/servlet/authorization/expression-based.adoc
Labels: in: docs, status: feedback-provided

#7635 Remove unnecessary and inefficiency code
  core/src/main/java/org/springframework/security/access/expression/SecurityExpressionRoot.java
Labels: status: waiting-for-triage

#5509 Override the key to avoid CookieTheftException
  config/src/main/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurer.java
  config/src/test/java/org/springframework/security/config/annotation/web/configurers/RememberMeConfigurerTests.java
Labels: status: feedback-provided

#7573 Make jwks_uri optional for RFC 8414 and required for OpenID Connect
  oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/registration/ClientRegistrations.java
  oauth2/oauth2-client/src/test/java/org/springframework/security/oauth2/client/registration/ClientRegistrationsTest.java
  oauth2/oauth2-jose/src/main/java/org/springframework/security/oauth2/jwt/JwtDecoderProviderConfigurationUtils.java
  oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/JwtDecodersTests.java
  oauth2/oauth2-jose/src/test/java/org/springframework/security/oauth2/jwt/ReactiveJwtDecodersTests.java
Labels: in: oauth2, status: duplicate, type: enhancement

#7557 Adds UserCache to the DaoAuthenticationprovider through AuthenticationConfiguration
  config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
Labels: status: feedback-provided

#7659 Fix typo in log message in GlobalMethodSecurityBeanDefinitionParser.java.
  config/src/main/java/org/springframework/security/config/method/GlobalMethodSecurityBeanDefinitionParser.java
Labels: status: waiting-for-triage

#7673 fix typo: require require
  docs/manual/src/docs/asciidoc/_includes/about/exploits/csrf.adoc
  docs/manual/src/docs/asciidoc/_includes/about/getting-spring-security.adoc
  docs/manual/src/docs/asciidoc/_includes/reactive/exploits/headers.adoc
  docs/manual/src/docs/asciidoc/_includes/servlet/exploits/headers.adoc
  docs/manual/src/docs/asciidoc/_includes/servlet/saml2/saml2-login.adoc
Labels: status: waiting-for-triage

#7663 Fix minor typo.
  docs/manual/src/docs/asciidoc/_includes/servlet/java-configuration/index.adoc
Labels: status: waiting-for-triage

#7678 Log full failed authentication exception in BasicAuthenticationFilter
  web/src/main/java/org/springframework/security/web/authentication/www/BasicAuthenticationFilter.java
Labels: in: web, type: enhancement

#7666 Fix InitializeAuthenticationProviderBeanManagerConfigurer Javadoc
  config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeAuthenticationProviderBeanManagerConfigurer.java
  config/src/main/java/org/springframework/security/config/annotation/authentication/configuration/InitializeUserDetailsBeanManagerConfigurer.java
Labels: in: docs, type: enhancement
