Repository spring-projects/spring-security, pull requests merged in 2022-09, with the labels that each got.

#11781 Add new interfaces for CSRF request processing
  config/src/main/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurer.java
  config/src/main/java/org/springframework/security/config/http/CsrfBeanDefinitionParser.java
  config/src/main/resources/org/springframework/security/config/spring-security-5.8.rnc
  config/src/main/resources/org/springframework/security/config/spring-security-5.8.xsd
  config/src/test/java/org/springframework/security/config/annotation/web/configuration/DeferHttpSessionJavaConfigTests.java
  config/src/test/java/org/springframework/security/config/annotation/web/configurers/CsrfConfigurerTests.java
  config/src/test/java/org/springframework/security/config/http/CsrfConfigTests.java
  config/src/test/resources/org/springframework/security/config/http/CsrfConfigTests-WithRequestAttrName.xml
  config/src/test/resources/org/springframework/security/config/http/DeferHttpSessionTests-Explicit.xml
  docs/modules/ROOT/pages/servlet/appendix/namespace/http.adoc
  web/src/main/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategy.java
  web/src/main/java/org/springframework/security/web/csrf/CsrfFilter.java
  web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestAttributeHandler.java
  web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestProcessor.java
  web/src/main/java/org/springframework/security/web/csrf/CsrfTokenRequestResolver.java
  web/src/test/java/org/springframework/security/web/csrf/CsrfAuthenticationStrategyTests.java
  web/src/test/java/org/springframework/security/web/csrf/CsrfFilterTests.java
  web/src/test/java/org/springframework/security/web/csrf/CsrfTokenRequestProcessorTests.java
Labels: in: web, type: enhancement

#11787 Add Antora Build to docs-build branch
  .editorconfig
  .github/actions/algolia-config.json
  .github/actions/algolia-docsearch-scraper.sh
  .github/actions/publish-docs.sh
  .github/workflows/deploy-docs.yml
  .github/workflows/rebuild-search-index.yml
  .gitignore
  .idea/checkstyle-idea.xml
  .idea/externalDependencies.xml
  .npmrc
  .sdkmanrc
  antora-playbook-with-worktrees.yml
  antora-playbook.yml
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/antora/extensions/antora-linked-worktree-patch.js
  lib/antora/extensions/major-minor-segment.js
  lib/antora/extensions/version-fix.js
  package.json
Labels: in: docs

#11797 build and publish RC versions
  antora-playbook.yml
Labels: in: build, type: task

#11798 reconfigure main branch for local builds and as scheduler for docs workflows
  .github/actions/algolia-config.json
  .github/actions/algolia-deploy.sh
  .github/actions/algolia-docsearch-scraper.sh
  .github/workflows/algolia-index.yml
  .github/workflows/deploy-docs.yml
  .github/workflows/deploy-reference.yml
  .github/workflows/rebuild-search-index.yml
  .github/workflows/trigger-deploy-docs.yml
  .github/workflows/trigger-rebuild-search-index.yml
  docs/.gitignore
  docs/antora-linked-worktree-patch.js
  docs/antora-playbook.yml
  docs/antora.yml
  docs/antora/extensions/major-minor-segment.js
  docs/antora/extensions/version-fix.js
  docs/local-antora-playbook.yml
  docs/package.json
  docs/spring-security-docs.gradle
Labels: in: docs, type: task

#11806 fix docs publish script and trigger workflow on correct branch name
  .github/actions/publish-docs.sh
  .github/workflows/deploy-docs.yml
Labels: status: waiting-for-triage

#11807 propagate exit code in publish-docs script
  .github/actions/publish-docs.sh
Labels: status: waiting-for-triage

#11808 Add Antora Collector to eliminate the dependency on the generated-docs repository
  antora-playbook-with-worktrees.yml
  antora-playbook.yml
  lib/antora/extensions/inject-collector-config.js
  package.json
Labels: status: waiting-for-triage

#11809 repurpose 5.8.x branch to provide local docs build
  .github/actions/algolia-config.json
  .github/actions/algolia-deploy.sh
  .github/actions/algolia-docsearch-scraper.sh
  .github/workflows/algolia-index.yml
  .github/workflows/deploy-reference.yml
  docs/.gitignore
  docs/antora-linked-worktree-patch.js
  docs/antora-playbook.yml
  docs/antora.yml
  docs/antora/extensions/major-minor-segment.js
  docs/antora/extensions/root-component-name.js
  docs/antora/extensions/version-fix.js
  docs/local-antora-playbook.yml
  docs/package.json
  docs/spring-security-docs.gradle
  local-antora-playbook.yml
Labels: status: waiting-for-triage

#11810 repurpose 5.7.x branch to provide local docs build
  .github/actions/algolia-config.json
  .github/actions/algolia-deploy.sh
  .github/actions/algolia-docsearch-scraper.sh
  .github/workflows/algolia-index.yml
  .github/workflows/deploy-reference.yml
  docs/.gitignore
  docs/antora-linked-worktree-patch.js
  docs/antora-playbook.yml
  docs/antora.yml
  docs/antora/extensions/major-minor-segment.js
  docs/antora/extensions/root-component-name.js
  docs/antora/extensions/version-fix.js
  docs/local-antora-playbook.yml
  docs/package.json
  docs/spring-security-docs.gradle
  local-antora-playbook.yml
Labels: status: waiting-for-triage

#11811 repurpose 5.6.x branch to provide local docs build
  .github/actions/algolia-config.json
  .github/actions/algolia-deploy.sh
  .github/actions/algolia-docsearch-scraper.sh
  .github/workflows/algolia-index.yml
  .github/workflows/deploy-reference.yml
  docs/.gitignore
  docs/antora-linked-worktree-patch.js
  docs/antora-playbook.yml
  docs/antora.yml
  docs/antora/extensions/major-minor-segment.js
  docs/antora/extensions/root-component-name.js
  docs/local-antora-playbook.yml
  docs/package.json
  docs/spring-security-docs.gradle
  local-antora-playbook.yml
Labels: status: waiting-for-triage

#11874 add a README that documents how to build the docs
  README.adoc
Labels: status: waiting-for-triage

#11876 add information to README describing how to build the reference docs
  README.adoc
Labels: in: docs, type: enhancement

#11756 Simplify AuthorizationManager composition
  core/src/main/java/org/springframework/security/authorization/AuthorizationManagers.java
  core/src/test/java/org/springframework/security/authorization/AuthorizationManagersTests.java
Labels: status: duplicate, in: core, type: enhancement

#11789 Remove Deprecated OpenSAML 3 Support
  build.gradle
  config/spring-security-config.gradle
  config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurer.java
  config/src/main/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LogoutConfigurer.java
  config/src/test/java/org/springframework/security/config/annotation/web/configurers/saml2/Saml2LoginConfigurerTests.java
  docs/modules/ROOT/pages/servlet/saml2/login/overview.adoc
  docs/modules/ROOT/pages/whats-new.adoc
  gradle.properties
  saml2/saml2-service-provider/spring-security-saml2-service-provider.gradle
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSaml4AuthenticationRequestResolver.java
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutRequestResolver.java
  saml2/saml2-service-provider/src/main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutResponseResolver.java
  saml2/saml2-service-provider/src/opensaml3Main/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSaml3AuthenticationRequestResolver.java
  saml2/saml2-service-provider/src/opensaml3Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml3LogoutRequestResolver.java
  saml2/saml2-service-provider/src/opensaml3Main/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml3LogoutResponseResolver.java
  saml2/saml2-service-provider/src/opensaml3Test/java/org/springframework/security/saml2/provider/service/authentication/OpenSamlAuthenticationProviderTests.java
  saml2/saml2-service-provider/src/opensaml3Test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml3LogoutRequestResolverTests.java
  saml2/saml2-service-provider/src/opensaml3Test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml3LogoutResponseResolverTests.java
  saml2/saml2-service-provider/src/opensaml4Main/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProvider.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/DefaultSaml2AuthenticatedPrincipalTests.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/authentication/OpenSaml4AuthenticationProviderTests.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/OpenSaml4AuthenticationRequestResolverTests.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutRequestResolverTests.java
  saml2/saml2-service-provider/src/test/java/org/springframework/security/saml2/provider/service/web/authentication/logout/OpenSaml4LogoutResponseResolverTests.java
Labels: in: saml2, type: breaks-passivity

#11882 Reduce severity of invalid registrationId to warn
  oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/DefaultOAuth2AuthorizationRequestResolver.java
  oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/InvalidClientRegistrationIdException.java
  oauth2/oauth2-client/src/main/java/org/springframework/security/oauth2/client/web/OAuth2AuthorizationRequestRedirectFilter.java
Labels: type: enhancement, in: oauth2

#11917 Configure ContentNegotiationStrategy in HttpSecurityConfiguration
  config/src/main/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfiguration.java
  config/src/test/java/org/springframework/security/config/annotation/web/configuration/HttpSecurityConfigurationTests.java
Labels: status: duplicate, in: config, type: enhancement

#11901 switch to official Antora Plugin for Gradle (docs-build branch)
  .npmrc
  antora-playbook-with-worktrees.yml
  antora-playbook.yml
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  lib/antora/extensions/inject-collector-config.js
  package.json
Labels: in: docs, type: task

#11911 Removed empty test classes SomeDomainObject/Manager
  core/src/test/java/org/springframework/security/access/vote/SomeDomainObject.java
  core/src/test/java/org/springframework/security/access/vote/SomeDomainObjectManager.java
Labels: in: core, type: task
